recipe: default.v1
assistant_id: mentara-professional-chatbot
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 2
  - name: DIETClassifier
    epochs: 50
    constrain_similarities: true
    model_confidence: softmax
    batch_strategy: balanced
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50
    constrain_similarities: true
    retrieval_intent: chitchat
  - name: FallbackClassifier
    threshold: 0.3

policies:
  - name: MemoizationPolicy
    max_history: 3
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
  - name: TEDPolicy
    max_history: 5
    epochs: 50
    constrain_similarities: true
  - name: UnexpecTEDIntentPolicy
    max_history: 3
    epochs: 50